# Generated by Django 5.2.7 on 2025-11-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_auto_20251121_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]